### ISSUE TITLE
Worker is not defined

### ISSUE THREAD

**Issue by joshuaquek** [developit/greenlet#6]
Got this error. I did a regular npm install and it cant seem to run.

```bash
ReferenceError: Worker is not defined
    at e (/Users/josh/Desktop/node-playground/node_modules/greenlet/dist/greenlet.js:1:87)
    at Object.<anonymous> (/Users/josh/Desktop/node-playground/examples/greenlet-multithread.js:3:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/josh/Desktop/node-playground/server.js:4:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! playground@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the playground@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

**Comment by joshuaquek** [comment]
My code that I'm running:

<img width="454" alt="screen shot 2018-01-29 at 5 00 23 pm" src="https://user-images.githubusercontent.com/5335756/35501794-eb46e3ae-0515-11e8-897c-de076c30bf74.png">

**Comment by chinanf-boy** [comment]
you may try run in browser

**Comment by michaelzoidl** [comment]
Maybe someone should note in the README that `greenlet` is Browser-Only? 
It uses Web-Workers which is not supported by node.

**Comment by carcinocron** [comment]
How hard would it be to add NodeJS support without breaking the API?

**Comment by HZSamir** [comment]
Quite interested in NodeJS support as well

**Comment by developit** [comment]
It seems like @joshuaquek PR'd to his fork - I'll update the readme to mention usage in Node requires [node-webworker](https://github.com/pgriess/node-webworker).

**Comment by Mijago** [comment]
Please note that node-webworker is out-of-date and has hard-to-solve issues on its own: https://github.com/pgriess/node-webworker/issues/47
